vaadin.launch-browser=true
spring.application.name=EventReservationSystem

# Configuration H2
spring.datasource.url=jdbc:h2:mem:eventdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# DÉSACTIVER data.sql
spring.sql.init.mode=never

# SPRING SECURITY
spring.security.user.name=admin
spring.security.user.password=admin

# Console H2
spring.h2.console.settings.web-allow-others=true

# VAADIN
vaadin.productionMode=false